### ISSUE TITLE
Open access of these publications is no longer available

### ISSUE THREAD

**Issue by philipskokoh** [Coleridge-Initiative/rclc#3]
Just found out that OpenAccess publications from `papers.ssrn.com` do not return pdf files.
Here are they:
```
[
{"@id": "https://github.com/Coleridge-Initiative/adrf-onto/wiki/Vocabulary#publication-b3712b3852b3c38fdeb7", "openAccess": "https://papers.ssrn.com/sol3/Delivery.cfm/19677.pdf?abstractid=2785275&mirid=1&type=2"},
{"@id": "https://github.com/Coleridge-Initiative/adrf-onto/wiki/Vocabulary#publication-f864820c2ac96be88d5d", "openAccess": "https://papers.ssrn.com/sol3/Delivery.cfm/SSRN_ID2640935_code536749.pdf?abstractid=2023843&mirid=1&type=2"},
{"@id": "https://github.com/Coleridge-Initiative/adrf-onto/wiki/Vocabulary#publication-f45c2734c942ab11ea19", "openAccess": "https://papers.ssrn.com/sol3/Delivery.cfm/3871.pdf?abstractid=2793911&mirid=1&type=2"}
]
```

**Comment by ceteri** [comment]
Thank you @philipskokoh -- looks like SSRN changed to require a login, even for the "Open PDF in Browser" option now.

Just updated to `v0.1.1`, adding more publications and datasets, and fixing those links:
https://github.com/Coleridge-Initiative/rclc/tree/v0.1.1

Those corrected links for open access PDFs are respectively:

 - https://www.econstor.eu/bitstream/10419/19677/1/200648dkp.pdf
 - https://www.clevelandfed.org/~/media/content/newsroom%20and%20events/publications/working%20papers/2014/wp%201421%20the%20role%20of%20relationships%20and%20liquidity%20needs%20pdf.pdf
 - https://www.econstor.eu/bitstream/10419/3871/1/200606dkp_b.pdf

Also, we've removed any SSRN links used for open access PDFs.
