### ISSUE TITLE
Convert into txt files PDFs that are images

### ISSUE THREAD

**Issue by HaritzPuerto** [Coleridge-Initiative/rclc#7]
Hi,

I discovered that 2b4497873374d080d359.pdf is not converted well into .txt. I only got an empty file. But the pdf is ok. Talking to @philipskokoh in the repo of his baseline we found out that it is because the pdf of the publication is actually a scanned document, so it is like an image rather than text. So the tools we are using right now to convert the pdf into txt don’t work since they need real text.

I think we only have one scanned (image) pdf for now. But it can be a limitation in the future and definitely something to take into account when augmenting the dataset. @ceteri 

Best,
Haritz

**Comment by ceteri** [comment]
Good catch!  We'll remove those from the corpus, where there's just a scan, unless we can find a PDF document that is open access.
